/**
 * Registry + rotation-selector unit tests for the menu diorama variant spine
 * (ticket 14 — the prefactor that turns the single forest-bonfire composition
 * into a multi-variant registry so ticket 15 can append themed variants).
 *
 * Scope — what these tests pin:
 *   - The registry resolves every registered `MenuDioramaVariantId` to a valid
 *     `{composition, placements, auraAnchor}` bundle (3 layers, non-empty
 *     placements, finite anchor).
 *   - An unknown id throws (fail-fast — no silent fallback to a wrong diorama).
 *   - `pickMenuDioramaVariant()` always returns a REGISTERED id, honors an
 *     injected seeded RNG (deterministic for tests), and uses `Math.random` by
 *     default (non-deterministic per boot = faithful "rotates every open").
 *   - **Byte-identical forest-bonfire composition + placements baseline**:
 *     the registry's `'forest-bonfire'` composition + placements deep-equal the
 *     captured JSON fixtures. The COMPOSITION fixture was REGENERATED by ticket
 *     27 (the authorized G1–G5 grammar rebuild — adds path_crossing/path_curve,
 *     moves wall_half to the 4 rotated rug corners, adds G3 grass→plants
 *     variation). It is the post-ticket-27 baseline. The PLACEMENTS fixture was
 *     regenerated by ticket 12 (the authorized 4-perimeter torch/lantern →
 *     biome-glow swap); ticket 27 did NOT change forest-bonfire's placements
 *     (still 1 campfire + 4 biome-glow), so that fixture is unchanged.
 *   - The prefactor shipped EXACTLY ONE registered variant (`'forest-bonfire'`);
 *     ticket 15 grew the roster to 8, and the menu redesign (c83ecd8 → 347a748)
 *     RETIRED the 4 weakest themes (ruined-courtyard, flooded-dungeon,
 *     secret-passage, graveyard-tomb) and appended 3 forest sub-themes
 *     (glade/ruins/creek) — the roster is now 7 (forest-forward: 4 forest
 *     sub-themes + 3 distinct interiors). The redesign also retuned the
 *     per-variant light rigs (several drop their crystals; ruins is a
 *     crystal lattice) — pinned in the EXPECTED_* tables below.
 *
 * The fixtures live in `__fixtures__/forest-bonfire-*.prechange.json`. They are
 * generated artifacts (the builders' serialized output) — DO NOT hand-edit;
 * regenerate by running the builders (tsx imports the registry + serializes).
 * The `composition` fixture was regenerated by ticket 27 (the grammar rebuild);
 * the `placements` fixture was regenerated by ticket 12 (the biome-glow swap)
 * and is unchanged by ticket 27.
 */
import { describe, it, expect } from 'vitest';
// Native JSON imports (resolveJsonModule is on; vitest/vite resolves the path
// relative to THIS module). The PLACEMENTS fixture is the post-redesign
// baseline (1 campfire hero + 2 torch + 2 lantern — the 2 emerald crystals
// were removed by 67f3626), regenerated from the builders' serialized output. The
// composition fixture was RETIRED: the Bomberman map grammar is now verified via
// structural assertions (border ring, pillar lattice, cover clusters) instead of
// byte-pinned JSON, which is more maintainable across composition changes.
import placementsFixture from './__fixtures__/forest-bonfire-placements.prechange.json';
import {
  getMenuDioramaVariant,
  getMenuDioramaComposition,
  getMenuDioramaPlacements,
  getMenuDioramaAuraAnchor,
  pickMenuDioramaVariant,
  MENU_DIORAMA_VARIANT_IDS,
  type MenuDioramaVariantId,
} from '../menuDioramaComposition.js';
import { LIGHT_PALETTE } from '../../../rendering/lighting/LightPalette.js';

// Re-serialize the placements fixture for the byte-identical comparison.
const PLACEMENTS_FIXTURE_JSON = JSON.stringify(placementsFixture);

// Phase 4 spec v2 P7/A1 — per-variant bake-haze tint ("same light, different
// air"). Each variant tints the far (α 0.28) + bg (α 0.12) haze toward a biome
// color (warm forest, cold crypt, moonlit glade, …) while the lighting spine
// stays identical. Pinned so a future edit can't silently re-unify them (which
// would erase the biome differentiation). REGENERATED for the menu-redesign
// roster (c83ecd8 → 347a748): the 4 weakest themes were retired and 3 forest
// sub-themes (glade/ruins/creek) were appended, each with its own tint.
const EXPECTED_HAZE: Record<string, number> = {
  'forest-bonfire': 0x473d2e, // warm baseline — the camp at dusk
  'forest-glade': 0x2a3848, // cool moonlit blue-grey — the serene grove
  'forest-ruins': 0x3a4030, // mossy green-grey — overgrown stone
  'forest-creek': 0x2a3a44, // cool wet blue-grey — the forest stream
  'crypt-antechamber': 0x2a3038, // cold blue-grey — the sealed tomb
  'armory-cache': 0x4a3520, // warm brown — the forge hall
  'temple-threshold': 0x4a3a20, // golden — the sacred threshold
};

// Per-variant CRYSTAL RIG — the menu redesign (67f3626 + 347a748) retuned the
// biome-glow crystals per variant: some rigs DROP their crystals entirely
// (forest-bonfire/crypt/temple — `crystalAt` calls removed; the fire is the
// sole hero), some are crystal-DOMINANT (forest-ruins' 14-crystal lattice,
// forest-glade's diamond, forest-creek's bank run). `count` is the exact
// shipped biome-glow placement count; `hue` is the color every crystal in
// that variant carries (null when count is 0). Pinned so a future edit can't
// silently re-unify or re-scatter them (which would erase the per-variant
// tuning the redesign shipped).
const EXPECTED_CRYSTALS: Readonly<
  Record<string, { count: number; hue: readonly [number, number, number] | null }>
> = {
  'forest-bonfire': { count: 0, hue: null }, // crystals removed — fire is the sole hero
  'forest-glade': { count: 5, hue: [0.3, 0.4, 0.52] }, // steel-blue moonlit diamond
  'forest-ruins': { count: 14, hue: [0.26, 0.16, 0.42] }, // spectral violet lattice
  'forest-creek': { count: 7, hue: [0.18, 0.45, 0.24] }, // emerald water's edge
  'crypt-antechamber': { count: 0, hue: null }, // crystals removed — candle vigil only
  'armory-cache': { count: 3, hue: [0.62, 0.36, 0.12] }, // ember-amber forge runes
  'temple-threshold': { count: 0, hue: null }, // crystals removed — gate frame only
};

// Per-variant TOTAL placement count (campfire/brazier hero + warm supports +
// crystals). The redesign loosened the old constant 7-budget into a per-variant
// rig; these pin the shipped totals.
const EXPECTED_PLACEMENT_COUNTS: Record<string, number> = {
  'forest-bonfire': 5,
  'forest-glade': 5,
  'forest-ruins': 14,
  'forest-creek': 7,
  'crypt-antechamber': 5,
  'armory-cache': 7,
  'temple-threshold': 5,
};

// ─── Registry resolution ─────────────────────────────────────────────────────

describe('14 variant registry — resolution contract', () => {
  it('every registered id resolves a full variant bundle (composition + placements + auraAnchor)', () => {
    for (const id of MENU_DIORAMA_VARIANT_IDS) {
      const variant = getMenuDioramaVariant(id);
      // composition: exactly 5 layers (ticket 28: far/bg/mid/fg/fore).
      expect(variant.composition).toHaveLength(5);
      const layerIds = variant.composition.map((l) => l.id).sort();
      expect(layerIds).toEqual(['bg', 'far', 'fg', 'fore', 'mid']);
      // placements: non-empty (at least the central campfire).
      expect(variant.placements.length).toBeGreaterThan(0);
      // auraAnchor: finite grid coords (the aura light position).
      expect(Number.isFinite(variant.auraAnchor.gridX)).toBe(true);
      expect(Number.isFinite(variant.auraAnchor.gridY)).toBe(true);
    }
  });

  it('getMenuDioramaComposition / getMenuDioramaPlacements / getMenuDioramaAuraAnchor agree with getMenuDioramaVariant', () => {
    for (const id of MENU_DIORAMA_VARIANT_IDS) {
      const variant = getMenuDioramaVariant(id);
      expect(getMenuDioramaComposition(id)).toBe(variant.composition);
      expect(getMenuDioramaPlacements(id)).toBe(variant.placements);
      expect(getMenuDioramaAuraAnchor(id)).toBe(variant.auraAnchor);
    }
  });

  it('throws on an unknown variant id (fail-fast — no silent wrong diorama)', () => {
    // Cast: the registry API types `id` as `MenuDioramaVariantId` (a union); the
    // runtime guard exists precisely for the case where a caller bypasses the
    // type (JSON, typo, future id not yet in VARIANTS). Simulate via `as`.
    const unknown = 'desert-oasis-not-registered' as MenuDioramaVariantId;
    expect(() => getMenuDioramaVariant(unknown)).toThrow(/unknown variant id/);
    expect(() => getMenuDioramaComposition(unknown)).toThrow(/unknown variant id/);
    expect(() => getMenuDioramaPlacements(unknown)).toThrow(/unknown variant id/);
    expect(() => getMenuDioramaAuraAnchor(unknown)).toThrow(/unknown variant id/);
  });

  it('the throw message lists the registered ids (diagnoses the typo)', () => {
    const unknown = 'typo' as MenuDioramaVariantId;
    try {
      getMenuDioramaVariant(unknown);
      throw new Error('expected throw');
    } catch (err) {
      const msg = (err as Error).message;
      // The message includes the registered ids so a developer can spot the typo.
      for (const id of MENU_DIORAMA_VARIANT_IDS) {
        expect(msg).toContain(id);
      }
    }
  });
});

// ─── Rotation selector ───────────────────────────────────────────────────────

describe('14 variant registry — rotation selector', () => {
  it('pickMenuDioramaVariant always returns a REGISTERED id (never an unregistered one)', () => {
    const registered = new Set<string>(MENU_DIORAMA_VARIANT_IDS);
    // Sample many times with the default RNG (Math.random) — every draw must be
    // a registered id. (Ticket 15 grew the roster to 8, so draws now vary; the
    // contract is still "always a registered id.")
    for (let i = 0; i < 50; i++) {
      const id = pickMenuDioramaVariant();
      expect(registered.has(id)).toBe(true);
    }
  });

  it('honors an injected seeded RNG (deterministic for tests)', () => {
    // A constant RNG that returns 0 → idx 0 → the first registered id.
    expect(pickMenuDioramaVariant(() => 0)).toBe(MENU_DIORAMA_VARIANT_IDS[0]);
    // An RNG that returns 0.999... → clamped to the LAST registered id (the
    // `Math.min` clamp guards the `rng() === 1` edge).
    expect(pickMenuDioramaVariant(() => 0.999999)).toBe(
      MENU_DIORAMA_VARIANT_IDS[MENU_DIORAMA_VARIANT_IDS.length - 1],
    );
  });

  it('the default RNG is Math.random (non-deterministic per boot — NOT deterministic-by-bug)', () => {
    // The selector signature defaults `rng = Math.random` — verified by the
    // fact that the default produces a registered id across many calls WITHOUT
    // the caller passing anything (the "seeded so it's not deterministic-by-bug"
    // ticket requirement is satisfied by sourcing the RNG explicitly).
    // We cannot assert non-determinism directly (Math.random could theoretically
    // repeat), but we assert the contract: the default path draws from the full
    // registered set over enough samples. (Ticket 15: 8 variants registered, so
    // a 20-draw sample typically sees several distinct ids.)
    const draws = new Set<string>();
    for (let i = 0; i < 20; i++) {
      draws.add(pickMenuDioramaVariant());
    }
    // Every draw was a registered id (the union of draws ⊆ registered set).
    for (const d of draws) {
      expect((MENU_DIORAMA_VARIANT_IDS as readonly string[]).includes(d)).toBe(true);
    }
  });

  it('with 7 registered variants, a seeded RNG cycle returns EVERY id (full rotation coverage)', () => {
    // Ticket 15 grew the roster 1 → 8; the menu redesign (c83ecd8 → 347a748)
    // retired 4 themes + appended 3 forest sub-themes → 7. A deterministic RNG
    // that emits i/N for i in [0..N) walks the selector across every index →
    // every registered id is returned exactly once. This is the "rotates across
    // the full roster" contract.
    const N = MENU_DIORAMA_VARIANT_IDS.length;
    expect(N).toBe(7);
    const seen = new Set<string>();
    for (let i = 0; i < N; i++) {
      const id = pickMenuDioramaVariant(() => i / N);
      seen.add(id);
    }
    expect(seen.size).toBe(N);
    for (const id of MENU_DIORAMA_VARIANT_IDS) expect(seen.has(id)).toBe(true);
  });
});

// ─── Forest-bonfire: Bomberman map structure (structural assertions) ────
//
// Replaces the old byte-identical fixture comparison. The Bomberman map grammar
// is verified via structural properties (border ring, hearth, pillars, cover,
// loot) instead of byte-pinned JSON — more maintainable across composition changes.

describe('forest-bonfire — Bomberman map structure', () => {
  it('has a complete border wall ring with rotated side walls + 4 corners', () => {
    const mid = getMenuDioramaComposition('forest-bonfire').find((l) => l.id === 'mid')!;
    // Top + bottom rows: horizontal wall tiles (rotation undefined = 0°)
    for (let col = 0; col <= 15; col++) {
      expect(mid.tiles.some((t) => t.col === col && t.row === 0 && t.frame === 'wall')).toBe(true);
      expect(mid.tiles.some((t) => t.col === col && t.row === 8 && t.frame === 'wall')).toBe(true);
    }
    // Left border (col 0, rows 1–7): wall tiles rotated 90° CW (vertical)
    for (let row = 1; row <= 7; row++) {
      const left = mid.tiles.find((t) => t.col === 0 && t.row === row && t.frame === 'wall');
      expect(left).toBeDefined();
      expect(left!.rotation).toBe(90);
    }
    // Right border (col 15, rows 1–7): wall tiles rotated 270° CW (mirror)
    for (let row = 1; row <= 7; row++) {
      const right = mid.tiles.find((t) => t.col === 15 && t.row === row && t.frame === 'wall');
      expect(right).toBeDefined();
      expect(right!.rotation).toBe(270);
    }
    // 4 wall_corners with rotations {0, 90, 180, 270}
    const corners = mid.tiles.filter((t) => t.frame === 'wall_corner');
    expect(corners).toHaveLength(4);
    const rotations = new Set(corners.map((t) => t.rotation ?? 0));
    for (const expected of [0, 90, 180, 270]) {
      expect(rotations.has(expected)).toBe(true);
    }
  });

  it('has a 2×2 tiles_center hearth centered on (7.5, 1.5)', () => {
    const mid = getMenuDioramaComposition('forest-bonfire').find((l) => l.id === 'mid')!;
    const hearth = mid.tiles.filter((t) => t.frame === 'tiles_center');
    expect(hearth).toHaveLength(4);
    for (const [c, r] of [[7, 1], [8, 1], [7, 2], [8, 2]]) {
      expect(hearth.some((t) => t.col === c && t.row === r)).toBe(true);
    }
  });

  it('has the redesigned minimal camp scatter — mirrored moss + the entrance aperture', () => {
    // The menu redesign (c83ecd8) replaced the ticket-15 camp tableaux
    // (barrels_stacked/crate/barrel/chair/chest/moss-at-14,6) with a minimal
    // atmospheric scatter: 2 mirrored moss clusters framing the aisle + the
    // doorway aperture in the bottom-center wall (the camp entrance).
    const mid = getMenuDioramaComposition('forest-bonfire').find((l) => l.id === 'mid')!;
    // Mirrored moss clusters (the emerald accents flanking the path aisle).
    expect(mid.tiles.some((t) => t.frame === 'plants' && t.col === 4 && t.row === 4)).toBe(true);
    expect(mid.tiles.some((t) => t.frame === 'plants' && t.col === 11 && t.row === 4)).toBe(true);
    // Aperture — a doorway in the bottom-center wall (the camp entrance).
    expect(mid.tiles.some((t) => t.frame === 'doorway' && t.col === 7 && t.row === 8)).toBe(true);
    expect(mid.tiles.some((t) => t.frame === 'doorway' && t.col === 8 && t.row === 8)).toBe(true);
    // The camp-tableaux props were REMOVED (scatter stays atmospheric — no
    // tall clutter in the glade). Guard against an accidental resurrection.
    for (const frame of ['barrels_stacked', 'crate', 'barrel', 'chair', 'chest']) {
      expect(mid.tiles.some((t) => t.frame === frame), `frame "${frame}" was removed by the redesign`).toBe(false);
    }
  });

  it('placements deep-equal the post-recomposition baseline fixture', () => {
    const placements = getMenuDioramaPlacements('forest-bonfire');
    expect(placements).toEqual(JSON.parse(PLACEMENTS_FIXTURE_JSON));
  });

  it('placements are exactly 5 fixtures — 1 campfire hero + 4 warm supports (crystals removed by the redesign)', () => {
    // The redesign (67f3626) removed forest-bonfire's 2 emerald crystals —
    // the campfire is the sole hero. 1 campfire + 2 torch + 2 lantern, all
    // forced to the unified campfire-orange (see the warm-unification test).
    const placements = getMenuDioramaPlacements('forest-bonfire');
    expect(placements).toHaveLength(5);
    expect(placements.filter((p) => p.kind === 'campfire')).toHaveLength(1);
    expect(placements.filter((p) => p.kind === 'biome-glow')).toHaveLength(0);
  });

  it('aura anchor is (7.5, 1.5) — behind the logo', () => {
    const anchor = getMenuDioramaAuraAnchor('forest-bonfire');
    expect(anchor.gridX).toBe(7.5);
    expect(anchor.gridY).toBe(1.5);
  });
});

// ─── Biome crystal placements (per-variant rig — redesign-tuned) ─────────────
//
// The menu redesign (67f3626 + 347a748) retuned the biome-glow crystals per
// variant instead of the ticket-15 constant "exactly 2 per variant": some rigs
// DROP their crystals (the fire is the sole hero), some are crystal-dominant
// (ruins' 14-crystal lattice). Every crystal that DOES ship carries its
// variant's hue via the per-placement `color` override, and the hues of the
// crystal-bearing variants are DISTINCT. These tests pin the shipped rig.

describe('biome crystal placements — per-variant rig (redesign-tuned)', () => {
  it('every variant ships its EXPECTED_CRYSTALS rig — exact count, one hue per variant', () => {
    for (const id of MENU_DIORAMA_VARIANT_IDS) {
      const expected = EXPECTED_CRYSTALS[id];
      if (!expected) throw new Error(`missing EXPECTED_CRYSTALS entry for ${id}`);
      const crystals = getMenuDioramaPlacements(id).filter((p) => p.kind === 'biome-glow');
      expect(crystals, `${id}: expected ${expected.count} crystals`).toHaveLength(expected.count);
      for (const c of crystals) {
        expect(c.color).toEqual(expected.hue);
      }
    }
  });

  it('every crystal stays OFF the button UI stage (cols 6–9, rows 4–6)', () => {
    // The menu buttons render over cols 6–9, rows 4–6 — the redesign kept every
    // crystal clear of that zone (crystal pools read as atmosphere, never as
    // glare behind the buttons).
    for (const id of MENU_DIORAMA_VARIANT_IDS) {
      const crystals = getMenuDioramaPlacements(id).filter((p) => p.kind === 'biome-glow');
      const intruders = crystals.filter(
        (c) => c.gridX >= 6 && c.gridX <= 9 && c.gridY >= 4 && c.gridY <= 6,
      );
      expect(intruders, `${id}: crystal sits behind the menu buttons`).toEqual([]);
    }
  });

  it('the crystal hues are DISTINCT (each crystal-bearing variant its own flavour — not generic blue)', () => {
    // NO two crystal-bearing variants share a crystal hue, and NONE is the
    // shipped biome-glow blue [0.4, 0.68, 1.0]. Rounded so float noise can't
    // fake a distinction.
    const SHIPPED_BLUE = [0.4, 0.68, 1.0] as const;
    const blueSig = SHIPPED_BLUE.map((c: number) => Number(c.toFixed(3))).join(',');
    const hues = new Set<string>();
    let crystalBearing = 0;
    for (const id of MENU_DIORAMA_VARIANT_IDS) {
      const hue = EXPECTED_CRYSTALS[id]!.hue;
      if (!hue) continue; // crystal-free rig — nothing to pin here
      crystalBearing++;
      const sig = hue.map((c: number) => Number(c.toFixed(3))).join(',');
      expect(sig, `${id}: crystal hue must not be the shipped biome-glow blue`).not.toBe(blueSig);
      expect(hues.has(sig), `${id}: crystal hue collides with another variant`).toBe(false);
      hues.add(sig);
    }
    expect(hues.size).toBe(crystalBearing);
  });

  it('every crystal hue is the 2nd tone — distinct from every warm-fire palette color (2-tone contract)', () => {
    // Tone 1 (the fire key + perimeter rig) is warm; the crystal hue is
    // tone 2. Pin that no variant's crystal hue collapses onto a warm-fire palette
    // color (which would erase the 2-tone separation the redesign shipped).
    const WARM = new Set(
      [
        LIGHT_PALETTE.campfire.color,
        LIGHT_PALETTE.brazier.color,
        LIGHT_PALETTE.torch.color,
        LIGHT_PALETTE.aura.color,
      ].map((c: readonly [number, number, number]) =>
        c.map((v: number) => Number(v.toFixed(2))).join(','),
      ),
    );
    for (const id of MENU_DIORAMA_VARIANT_IDS) {
      const hue = EXPECTED_CRYSTALS[id]!.hue;
      if (!hue) continue; // crystal-free rig — nothing to pin here
      const sig = hue.map((c: number) => Number(c.toFixed(2))).join(',');
      expect(WARM.has(sig), `${id}: crystal hue is byte-identical to a warm-fire color`).toBe(false);
    }
  });
});

// ─── Prefactor scope + 15-append contract ────────────────────────────────────

describe('14 variant registry — prefactor scope + redesign roster contract', () => {
  it('ships with EXACTLY SEVEN registered variants (forest-forward redesign roster) — ordered', () => {
    // Ticket 15 grew the roster 1 → 8; the menu redesign (c83ecd8 → 347a748)
    // retired the 4 weakest/most-redundant themes (ruined-courtyard,
    // flooded-dungeon, secret-passage, graveyard-tomb) and appended 3 forest
    // sub-themes. The order is the display/rotation order; forest-bonfire
    // stays first.
    expect(MENU_DIORAMA_VARIANT_IDS).toEqual([
      'forest-bonfire',
      'forest-glade',
      'forest-ruins',
      'forest-creek',
      'crypt-antechamber',
      'armory-cache',
      'temple-threshold',
    ]);
  });

  it('the variant id union + the ordered list + the VARIANTS registry agree (single source of truth)', () => {
    // The three registration sites (the `MenuDioramaVariantId` union is checked
    // at compile time; the runtime list + registry are checked here). 15 must
    // keep all three in sync — this test catches a future drift where someone
    // adds an id to the union but forgets the list or the registry.
    // (Compile-time: if a id is in the union but not the registry, the
    // `VARIANTS: Record<MenuDioramaVariantId, ...>` type would fail to compile.
    // Runtime: this test pins the list ↔ registry relationship.)
    for (const id of MENU_DIORAMA_VARIANT_IDS) {
      // Every listed id resolves (no throw) — i.e. the list ⊆ registry keys.
      expect(() => getMenuDioramaVariant(id)).not.toThrow();
    }
    // The list has no duplicates.
    expect(new Set(MENU_DIORAMA_VARIANT_IDS).size).toBe(MENU_DIORAMA_VARIANT_IDS.length);
  });
});

// ─── Ticket 15 contracts (8 themed variants) ─────────────────────────────────
//
// These pin the ticket-15 acceptance criteria that aren't covered by the
// resolution/selector tests above:
//   - Every composition frame is a REAL `game` atlas frame (no invented frames).
//   - Every placement kind is a valid `LightKind`.
//   - Every variant's auraAnchor matches a placement coord (the central light
//     sits at the anchor — the aura is co-located with the blaze).
//   - Every variant's BG layer covers the full 16×9 grid (the Canvas no-black
//     invariant — no variant goes black on the unlit fallback path).
//   - Each variant has a distinct terrain base (distinct scene vocabulary, not
//     8 reshuffles of the same floor).

// The real `game` atlas frame set — loaded from the shipped asset JSON so the
// frame-existence guard tests the ACTUAL atlas, not a hand-maintained list.
import gameAtlas from '../../../../public/assets/game.json';

const GAME_ATLAS_FRAMES: ReadonlySet<string> = new Set(
  ((gameAtlas as { textures: { frames: { filename: string }[] }[] }).textures[0]?.frames ?? []).map(
    (f) => f.filename,
  ),
);

// The canonical LightKind union (`packages/shared/src/map/tiledTypes.ts`). Keep
// in sync with the source union — this is the runtime guard the type system
// cannot enforce for data read from the registry.
const VALID_LIGHT_KINDS = new Set([
  'torch',
  'campfire',
  'candle',
  'biome-glow',
  'barrel-fire',
  'fireplace',
  'brazier',
  'lantern',
]);

describe('15 themed variants — atlas-frame + light-kind + anchor + coverage contracts', () => {
  it('every composition frame exists in the game atlas (no invented frames)', () => {
    for (const id of MENU_DIORAMA_VARIANT_IDS) {
      const composition = getMenuDioramaComposition(id);
      for (const layer of composition) {
        for (const tile of layer.tiles) {
          expect(GAME_ATLAS_FRAMES.has(tile.frame)).toBe(true);
        }
      }
    }
  });

  it('every placement kind is a valid LightKind', () => {
    for (const id of MENU_DIORAMA_VARIANT_IDS) {
      for (const p of getMenuDioramaPlacements(id)) {
        expect(VALID_LIGHT_KINDS.has(p.kind)).toBe(true);
      }
    }
  });

  it('every variant has exactly 5 layers (far/bg/mid/fg/fore) with the ticket-28 scrollFactors', () => {
    // Ticket 28 (doc 19): the composition grew from 3 layers to 5. far/bg < 1.0,
    // MID = 1.0 MANDATORY, fg/fore > 1.0. The fg layer IS the 'near' layer
    // (sf 1.3) — kept under its legacy id so the byte-pinned ticket-27 bg/mid/fg
    // tile arrays stay unchanged (append-only).
    for (const id of MENU_DIORAMA_VARIANT_IDS) {
      const composition = getMenuDioramaComposition(id);
      expect(composition.map((l) => l.id).sort()).toEqual(['bg', 'far', 'fg', 'fore', 'mid']);
      const far = composition.find((l) => l.id === 'far')!;
      const bg = composition.find((l) => l.id === 'bg')!;
      const mid = composition.find((l) => l.id === 'mid')!;
      const fg = composition.find((l) => l.id === 'fg')!;
      const fore = composition.find((l) => l.id === 'fore')!;
      expect(far.scrollFactor).toBe(0.45);
      expect(bg.scrollFactor).toBe(0.7);
      expect(mid.scrollFactor).toBe(1.0); // MANDATORY (all light anchors).
      expect(fg.scrollFactor).toBe(1.3);
      expect(fore.scrollFactor).toBe(1.6);
    }
  });

  it('every variant has a foreground silhouette (fore) layer framing the top + upper edges, center open', () => {
    // Ticket 28: the "looking through" read — dark canopy/arch across the top +
    // upper edges. The center (cols 5–10) MUST stay open so the logo + hearth
    // are unobstructed (doc 19 §2b caveat — legibility constraint).
    for (const id of MENU_DIORAMA_VARIANT_IDS) {
      const fore = getMenuDioramaComposition(id).find((l) => l.id === 'fore')!;
      expect(fore.tiles.length).toBeGreaterThan(0);
      // No fore tile intrudes on the central stage (cols 5–10).
      const intruders = fore.tiles.filter((t) => t.col >= 5 && t.col <= 10);
      expect(intruders).toEqual([]);
      // All fore tiles live at row 0 or row 1 (the top + upper edges).
      for (const t of fore.tiles) {
        expect(t.row).toBeLessThanOrEqual(1);
      }
    }
  });

  it('every variant applies its per-variant bake-haze tint on far (α 0.28) + bg (α 0.12) ONLY', () => {
    // Phase 4 spec v2 P7/A1: per-variant haze tint differentiates biomes (warm
    // forest, cold crypt, blue flooded, …) while the lighting spine stays
    // identical. far + bg carry the SAME per-variant tint at α 0.28 / 0.12; mid
    // (the nearest plane, where props + light anchors live) stays UNHAZED so it
    // is the darkest + most saturated band (correct atmospheric perspective);
    // fg/fore stay clean (fore's open center must not be filled by a wash).
    for (const id of MENU_DIORAMA_VARIANT_IDS) {
      const composition = getMenuDioramaComposition(id);
      const far = composition.find((l) => l.id === 'far')!;
      const bg = composition.find((l) => l.id === 'bg')!;
      const mid = composition.find((l) => l.id === 'mid')!;
      const fg = composition.find((l) => l.id === 'fg')!;
      const fore = composition.find((l) => l.id === 'fore')!;
      expect(far.hazeAlpha).toBe(0.28);
      expect(bg.hazeAlpha).toBe(0.12);
      expect(far.hazeColor).toBe(EXPECTED_HAZE[id]);
      expect(bg.hazeColor).toBe(EXPECTED_HAZE[id]); // same tint on both layers
      expect(mid.hazeAlpha).toBeUndefined(); // nearest plane — no haze
      expect(fg.hazeAlpha).toBeUndefined();
      expect(fore.hazeAlpha).toBeUndefined();
    }
  });

  it('every BG layer covers the full 16×9 grid (Canvas no-black invariant)', () => {
    for (const id of MENU_DIORAMA_VARIANT_IDS) {
      const bg = getMenuDioramaComposition(id).find((l) => l.id === 'bg')!;
      const cells = new Set(bg.tiles.map((t) => `${t.col},${t.row}`));
      expect(cells.size).toBe(144);
      for (let col = 0; col < 16; col++) {
        for (let row = 0; row < 9; row++) {
          expect(cells.has(`${col},${row}`)).toBe(true);
        }
      }
    }
  });

  it('every auraAnchor (7.5, 1.5) matches a placement coord (central light co-located with aura)', () => {
    for (const id of MENU_DIORAMA_VARIANT_IDS) {
      const anchor = getMenuDioramaAuraAnchor(id);
      expect(anchor.gridX).toBe(7.5);
      expect(anchor.gridY).toBe(1.5);
      const placements = getMenuDioramaPlacements(id);
      const centralAtAnchor = placements.find(
        (p) => p.gridX === anchor.gridX && p.gridY === anchor.gridY,
      );
      expect(centralAtAnchor).toBeDefined();
      // The central light is a campfire hero (bonfire/crypt/temple) or, for the
      // redesign's crystal-dominant variants (glade/ruins/creek/armory), a
      // biome-glow crystal sitting at the anchor.
      expect(['campfire', 'biome-glow']).toContain(centralAtAnchor!.kind);
    }
  });

  it('each variant ships its EXPECTED_PLACEMENT_COUNTS rig (per-variant light budgets)', () => {
    // The redesign loosened the ticket-15 constant 7-budget into per-variant
    // rigs (see EXPECTED_PLACEMENT_COUNTS): warm rigs are 5 (hero + 4
    // supports), crystal-dominant rigs are 5–14. The central light always
    // sits at the aura anchor (7.5, 1.5).
    for (const id of MENU_DIORAMA_VARIANT_IDS) {
      const placements = getMenuDioramaPlacements(id);
      expect(placements, `${id}: placement count drifted from the redesign rig`).toHaveLength(
        EXPECTED_PLACEMENT_COUNTS[id]!,
      );
      const central = placements.find((p) => p.gridX === 7.5 && p.gridY === 1.5);
      expect(central, `${id}: no central light at the aura anchor`).toBeDefined();
      expect(['campfire', 'biome-glow']).toContain(central!.kind);
    }
  });

  it('the 8 variants use distinct terrain base floors (distinct scene vocabularies)', () => {
    // Pin that each variant reads as a DIFFERENT scene — not 8 reshuffles of
    // the same floor. Extract the dominant BG frame per variant (the base
    // floor). Two variants MAY share a base (crypt/flooded/secret-passage all
    // use tiles_cracked) but must differ in vocabulary — so we additionally
    // require the full tile-set signature to be unique per variant.
    const signatures = new Map<string, Set<string>>();
    for (const id of MENU_DIORAMA_VARIANT_IDS) {
      const composition = getMenuDioramaComposition(id);
      const frames = new Set<string>();
      for (const layer of composition) for (const t of layer.tiles) frames.add(t.frame);
      // Each variant's full frame-set signature must be unique.
      expect(signatures.has(id)).toBe(false);
      signatures.set(id, frames);
    }
    const sigJsons = new Set<string>();
    for (const [id, frames] of signatures) {
      const sig = JSON.stringify([...frames].sort());
      // A signature colliding with another variant would mean two variants
      // use the identical frame vocabulary — i.e. a reshuffle, not a distinct
      // scene. All 8 must differ.
      expect(sigJsons.has(sig)).toBe(false);
      sigJsons.add(sig);
    }
  });
});

// ─── Map grammar contract (Bomberman structure applied to EVERY variant) ────
//
// These assertions pin the load-bearing invariants of the cinematic diorama
// design (boardroom session 1 — layered hierarchy + per-variant geometry):
//   - Floor underlay covers the full 16×9 grid with opaque tiles (no-black).
//   - Border ring with rotated side walls + 4 oriented corners (the arena frame).
//   - 2×2 hearth centered on the fire anchor (the focal pedestal).
//   - Scatter is bounded (3–14 props) — rich but never cluttered.
//   - The fire focal zone stays clear of scatter props.
//   - The button UI stage stays free of tall props (readability).
//   - Lighting is a composed rig (3–5 fixtures — the harmony budget).
//   - No light fixture stacks on a cover/loot prop (the regression guard).
//   - Each variant has a distinct frame-set vocabulary (8 different places).

describe('diorama composition contract — cinematic hierarchy applied to all 7 variants', () => {
  it('(M1) every BG layer covers the full 16×9 grid (no-black invariant)', () => {
    for (const id of MENU_DIORAMA_VARIANT_IDS) {
      const bg = getMenuDioramaComposition(id).find((l) => l.id === 'bg')!;
      const cells = new Set(bg.tiles.map((t) => `${t.col},${t.row}`));
      for (let col = 0; col < 16; col++) {
        for (let row = 0; row < 9; row++) {
          expect(cells.has(`${col},${row}`)).toBe(true);
        }
      }
    }
  });

  it('(M2) every MID has a border ring with rotated side walls + 4 oriented corners', () => {
    for (const id of MENU_DIORAMA_VARIANT_IDS) {
      const mid = getMenuDioramaComposition(id).find((l) => l.id === 'mid')!;
      // Left border walls rotated 90°, right border walls rotated 270°
      for (const row of [1, 2, 3, 4, 5, 6, 7]) {
        const left = mid.tiles.find((t) => t.col === 0 && t.row === row);
        expect(left).toBeDefined();
        expect(left!.rotation).toBe(90);
        const right = mid.tiles.find((t) => t.col === 15 && t.row === row);
        expect(right).toBeDefined();
        expect(right!.rotation).toBe(270);
      }
      // 4 wall_corners with rotations {0, 90, 180, 270}
      const corners = mid.tiles.filter((t) => t.frame === 'wall_corner');
      expect(corners).toHaveLength(4);
      const rotations = new Set(corners.map((t) => t.rotation ?? 0));
      for (const expected of [0, 90, 180, 270]) {
        expect(rotations.has(expected)).toBe(true);
      }
    }
  });

  it('(M6) every MID has a 2×2 hearth centered on (7.5, 1.5)', () => {
    for (const id of MENU_DIORAMA_VARIANT_IDS) {
      const mid = getMenuDioramaComposition(id).find((l) => l.id === 'mid')!;
      const HEARTH_FRAMES = new Set(['tile', 'tiles_center']);
      const hearth = mid.tiles.filter((t) => HEARTH_FRAMES.has(t.frame));
      expect(hearth.length).toBeGreaterThanOrEqual(4);
      for (const [c, r] of [[7, 1], [8, 1], [7, 2], [8, 2]]) {
        expect(hearth.some((t) => t.col === c && t.row === r)).toBe(true);
      }
    }
  });

  it('every MID scatter is bounded — rich but never cluttered (3–14 props)', () => {
    // Anti-clutter + anti-emptiness guard. The wall ring (50 tiles) + hearth (4)
    // are the shared base; scatter is the variant's own composed props. Cap at
    // 14 so a future edit can't regress to the wallpaper-every-corner layout;
    // floor at 3 so it can't regress to an empty stage either.
    for (const id of MENU_DIORAMA_VARIANT_IDS) {
      const mid = getMenuDioramaComposition(id).find((l) => l.id === 'mid')!;
      // Border ring is always 50 tiles (16+16+7+7+4) + hearth 4 = 54 base.
      const scatterApprox = mid.tiles.length - 54;
      expect(scatterApprox, `${id}: scatter ~${scatterApprox}, expected 3–14`).toBeLessThanOrEqual(14);
      expect(scatterApprox, `${id}: scatter ~${scatterApprox}, expected 3–14`).toBeGreaterThanOrEqual(3);
    }
  });

  it('every variant keeps the fire focal zone (cols 7–8, rows 1–2) clear of scatter', () => {
    // The fire + hearth own this zone — no props intrude so the blaze dominates.
    const SCATTER = new Set([
      'crate', 'crate_small', 'barrel', 'barrels_stacked', 'coffin', 'chest',
      'chair', 'plants', 'water', 'trapdoor_round', 'trapdoor_square',
      'stairs_down', 'weapon_longsword', 'weapon_bow', 'shield_curved', 'shield_straight',
      'track',
    ]);
    for (const id of MENU_DIORAMA_VARIANT_IDS) {
      const mid = getMenuDioramaComposition(id).find((l) => l.id === 'mid')!;
      const intruders = mid.tiles.filter(
        (t) => SCATTER.has(t.frame) && t.col >= 7 && t.col <= 8 && t.row >= 1 && t.row <= 2,
      );
      expect(intruders, `${id}: scatter props intrude on the fire focal zone`).toEqual([]);
    }
  });

  it('every variant keeps the button UI stage (cols 6–9, rows 4–6) free of tall props', () => {
    // The menu buttons render over cols 6–9, rows 4–6. Tall props (crates,
    // coffins, barrels, chests) behind them hurt readability — only low-weight
    // floor textures (path/track/puddle/tiles_corner) may pass through.
    const TALL = new Set(['crate', 'crate_small', 'barrel', 'barrels_stacked', 'coffin', 'chest', 'chair']);
    for (const id of MENU_DIORAMA_VARIANT_IDS) {
      const mid = getMenuDioramaComposition(id).find((l) => l.id === 'mid')!;
      const intruders = mid.tiles.filter(
        (t) => TALL.has(t.frame) && t.col >= 6 && t.col <= 9 && t.row >= 4 && t.row <= 6,
      );
      expect(intruders, `${id}: tall props behind the menu buttons`).toEqual([]);
    }
  });

  it('every variant keeps the warm tone unified — all warm fixtures forced to campfire-orange (tone 1)', () => {
    // Tone harmony: every warm fixture (any kind ≠ biome-glow) is forced to
    // TONE_WARM (campfire-orange) so the warm family never splits into a gold
    // 3rd tone. Crystals carry the variant hue (tone 2) — counts are per-variant
    // (EXPECTED_CRYSTALS); the warm/crystal COUNT split is no longer constant.
    const TONE_WARM_SIG = [1, 0.55, 0.22].map((v) => Number(v.toFixed(2))).join(',');
    for (const id of MENU_DIORAMA_VARIANT_IDS) {
      const placements = getMenuDioramaPlacements(id);
      const warm = placements.filter((p) => p.kind !== 'biome-glow');
      const crystals = placements.filter((p) => p.kind === 'biome-glow');
      expect(warm.length + crystals.length, `${id}: warm+crystals must be the full rig`).toBe(
        placements.length,
      );
      expect(crystals, `${id}: crystal count drifted from the redesign rig`).toHaveLength(
        EXPECTED_CRYSTALS[id]!.count,
      );
      for (const p of warm) {
        const sig = p.color!.map((v) => Number(v.toFixed(2))).join(',');
        expect(sig, `${id}: warm fixture not unified to campfire-orange`).toBe(TONE_WARM_SIG);
      }
    }
  });

  it('each variant has a distinct frame-set vocabulary', () => {
    const signatures = new Map<string, Set<string>>();
    for (const id of MENU_DIORAMA_VARIANT_IDS) {
      const composition = getMenuDioramaComposition(id);
      const frames = new Set<string>();
      for (const layer of composition) for (const t of layer.tiles) frames.add(t.frame);
      signatures.set(id, frames);
    }
    const sigJsons = new Set<string>();
    for (const [, frames] of signatures) {
      const sig = JSON.stringify([...frames].sort());
      expect(sigJsons.has(sig)).toBe(false);
      sigJsons.add(sig);
    }
  });

  it('NO light placement shares a tile with a cover/loot prop (no on-top stacking)', () => {
    // Regression guard for the "biome-glow on top of crates/coffins" complaint.
    // A light fixture (crystal / torch / candle / lantern / brazier / campfire)
    // must never render on top of a crate / coffin / barrel / chest — the
    // perimeter lights live in dedicated `LIGHT_NICHE` anchors that are disjoint
    // from the cover clusters + loot alcoves (see the coordinate budget docstring
    // in menuDioramaComposition.ts). Fractional placements (the central fire at
    // 7.5,1.5 — on the hearth) sit between tiles and are skipped (they render on
    // the hearth, never on a prop).
    const BLOCKING_FRAMES = new Set([
      'crate', 'crate_small', 'barrel', 'barrels_stacked', 'coffin', 'chest',
    ]);
    for (const id of MENU_DIORAMA_VARIANT_IDS) {
      const mid = getMenuDioramaComposition(id).find((l) => l.id === 'mid')!;
      const placements = getMenuDioramaPlacements(id);
      const blockingCells = new Set<string>();
      for (const t of mid.tiles) {
        if (BLOCKING_FRAMES.has(t.frame)) blockingCells.add(`${t.col},${t.row}`);
      }
      for (const p of placements) {
        if (!Number.isInteger(p.gridX) || !Number.isInteger(p.gridY)) continue;
        const key = `${p.gridX},${p.gridY}`;
        expect(
          blockingCells.has(key),
          `${id}: light '${p.kind}' at (${p.gridX},${p.gridY}) stacks on a cover/loot prop`,
        ).toBe(false);
      }
    }
  });
});
