export const SECTOR_GRID_SIZE = 4;
export const SECTOR_TILE_SIZE = 20;
export const TILE_PIXEL_SIZE = 128;
export const CORRIDOR_WIDTH = 3;

const ARENA_TILES = SECTOR_GRID_SIZE * SECTOR_TILE_SIZE;

export const GRID = {
  TILE_SIZE: TILE_PIXEL_SIZE,
  ARENA_WIDTH: ARENA_TILES,
  ARENA_HEIGHT: ARENA_TILES,
  WORLD_WIDTH: ARENA_TILES * TILE_PIXEL_SIZE,
  WORLD_HEIGHT: ARENA_TILES * TILE_PIXEL_SIZE,
  SECTOR_GRID_SIZE: SECTOR_GRID_SIZE,
  SECTOR_TILE_SIZE: SECTOR_TILE_SIZE,
  CORRIDOR_WIDTH: CORRIDOR_WIDTH,
} as const;
