export const TRAP = {
  SPIKE_DAMAGE: 25,
  SPIKE_COOLDOWN_TICKS: 60,
  SPIKE_STUN_DURATION: 0.5,
  SPIKE_KNOCKBACK: 128,
  FIRE_INSTANT_DAMAGE: 15,
  FIRE_DOT_PER_TICK: 5,
  FIRE_DOT_INTERVAL_TICKS: 60,
  FIRE_DURATION_TICKS: 300,
  FIRE_AREA_RADIUS: 1,
  TELEPORT_COOLDOWN_TICKS: 60,
  TRIGGER_RADIUS: 120,
} as const;
