import { describe, it, expect } from 'vitest';
import {
  LIGHT_PROP_TEXTURES,
  resolveLightPropTexture,
  LIGHT_PROP_ANIMS,
  BIOME_GLOW_PULSE_FRAMES,
  BIOME_CRYSTAL_FRAMES,
  BIOME_CRYSTAL_FRAME_DEFAULT,
} from '../LightPropResolver.js';

/**
 * Regression guard for the light-prop texture resolver (ticket 16).
 *
 * The contract ticket 17 consumes: every static `LightKind` the placer emits
 * (`torch`, `campfire`, `candle`, `biome-glow`) must map to a non-null
 * `{ atlas, frame }`; `campfire` must reuse the existing `game/campfire` frame
 * (no duplication); `barrel-fire` must not throw (barrels get no static prop).
 *
 * **Pixel-art fixture redesign (c83ecd8):** every flame kind is a STATIC
 * fixture-only sprite — the "living fire" feel comes from the LIGHT disk's
 * flicker (`TorchFlicker`), NOT sprite animation. All `LIGHT_PROP_ANIMS`
 * entries are empty; `biome-glow` is a single static frame. These tests pin
 * the static redesign (they previously pinned the 6-frame flicker anims).
 */
describe('LightPropResolver — kind -> prop texture mapping', () => {
  describe('resolveLightPropTexture', () => {
    it('maps torch to the lightProps atlas torch_01 frame', () => {
      const tex = resolveLightPropTexture('torch');
      expect(tex).not.toBeNull();
      expect(tex?.atlas).toBe('lightProps');
      expect(tex?.frame).toBe('torch_01');
    });

    it('REUSES the existing game/campfire frame for campfire (no duplication)', () => {
      // The ticket's hard rule: campfire art already exists in the game atlas;
      // the resolver must point there, not into the new sheet.
      const tex = resolveLightPropTexture('campfire');
      expect(tex).toEqual({ atlas: 'game', frame: 'campfire' });
    });

    it('maps candle to the lightProps atlas candle_01 frame', () => {
      const tex = resolveLightPropTexture('candle');
      expect(tex).not.toBeNull();
      expect(tex?.atlas).toBe('lightProps');
      expect(tex?.frame).toBe('candle_01');
    });

    it('maps biome-glow to the lightProps atlas biome-glow_01 frame', () => {
      const tex = resolveLightPropTexture('biome-glow');
      expect(tex).not.toBeNull();
      expect(tex?.atlas).toBe('lightProps');
      expect(tex?.frame).toBe('biome-glow_01');
    });

    it('returns null for barrel-fire (barrels get NO static prop; ticket 18)', () => {
      // Defensive: barrel-fire is in the shared LightKind union but barrels are
      // inert until they explode — no visible light fixture. Must not throw.
      expect(resolveLightPropTexture('barrel-fire')).toBeNull();
    });

    // ── Ticket 08 (A4): the three new fire-source kinds ──
    it('REUSES the game/campfire frame for fireplace (per REVIEW item B2)', () => {
      // The fireplace read relies on wall-adjacent indoor PLACEMENT (ticket 10),
      // not sprite distinction. The resolver points fireplace at the existing
      // campfire frame (no duplication, no new art for the fixture).
      const tex = resolveLightPropTexture('fireplace');
      expect(tex).toEqual({ atlas: 'game', frame: 'campfire' });
    });

    it('maps brazier to the lightProps atlas brazier_01 frame (distinct sprite)', () => {
      // Brazier gets its OWN distinct procedural sprite (a bowl of coals on a
      // stand), generated by generate_brazier_lantern.py. The first flicker
      // frame is brazier_01.
      const tex = resolveLightPropTexture('brazier');
      expect(tex).toEqual({ atlas: 'lightProps', frame: 'brazier_01' });
    });

    it('maps lantern to the lightProps atlas lantern_01 frame (distinct sprite)', () => {
      // Lantern gets its OWN distinct procedural sprite (an enclosed flame
      // behind glass in an iron frame), generated by generate_brazier_lantern.py.
      const tex = resolveLightPropTexture('lantern');
      expect(tex).toEqual({ atlas: 'lightProps', frame: 'lantern_01' });
    });

    it('every static placed kind (incl. the 3 new ticket-08 kinds) maps to a non-null texture', () => {
      // The kinds SECTOR_LIGHT_KIND_WEIGHTS places post-ticket-08 (per
      // LightPlacer): torch/campfire/candle/biome-glow/fireplace/brazier/lantern.
      const placedKinds = [
        'torch',
        'campfire',
        'candle',
        'biome-glow',
        'fireplace',
        'brazier',
        'lantern',
      ] as const;
      for (const kind of placedKinds) {
        const tex = resolveLightPropTexture(kind);
        expect(tex, `kind "${kind}" must resolve to a prop texture`).not.toBeNull();
        expect(tex?.atlas).toMatch(/^(game|lightProps)$/);
        expect(typeof tex?.frame).toBe('string');
        expect(tex?.frame.length).toBeGreaterThan(0);
      }
    });

    it('every static placed kind (torch/campfire/candle/biome-glow) maps to a non-null texture', () => {
      // The four kinds SECTOR_LIGHT_KIND_WEIGHTS actually places (per LightPlacer).
      const placedKinds = ['torch', 'campfire', 'candle', 'biome-glow'] as const;
      for (const kind of placedKinds) {
        const tex = resolveLightPropTexture(kind);
        expect(tex, `kind "${kind}" must resolve to a prop texture`).not.toBeNull();
        expect(tex?.atlas).toMatch(/^(game|lightProps)$/);
        expect(typeof tex?.frame).toBe('string');
        expect(tex?.frame.length).toBeGreaterThan(0);
      }
    });

    it('every resolved frame is a string and every atlas is a known AtlasKey', () => {
      for (const tex of Object.values(LIGHT_PROP_TEXTURES)) {
        if (tex === null) continue;
        expect(tex.atlas).toMatch(/^(game|ui|vfx|lightProps)$/);
        expect(typeof tex.frame).toBe('string');
      }
    });
  });

  describe('LIGHT_PROP_ANIMS — static fixtures (pixel-art fixture redesign)', () => {
    it('the torch has NO flicker frames — a static fixture-only sprite', () => {
      // c83ecd8 redesign: flame anims were removed — sprites that baked a
      // flame/glow into the art clashed with the pixel-art tiles. The torch
      // renders its static `torch_01` fixture; the flicker lives in the LIGHT
      // disk (TorchFlicker).
      expect(LIGHT_PROP_ANIMS.torch).toEqual([]);
    });

    it('the candle has NO flicker frames — a static fixture-only sprite', () => {
      // Same redesign ruling as the torch: the candle is a static sprite lit
      // by its flickering light disk.
      expect(LIGHT_PROP_ANIMS.candle).toEqual([]);
    });

    it('the neutral crystal frames exist for tinted menu crystals (BIOME_CRYSTAL_FRAMES)', () => {
      // c83ecd8 added the NEUTRAL crystal frame (a desaturated derivative of
      // biome-glow_01 built by scripts/asset-pipeline/build-neutral-crystal.ts)
      // so a single frame `setTint`s cleanly to any variant hue. The menu
      // diorama's per-variant crystals share this ONE frame + a per-placement
      // color override (LightPropRenderer swaps to it when `color` is present).
      expect(BIOME_CRYSTAL_FRAMES).toEqual(['biome-crystal_01']);
      expect(BIOME_CRYSTAL_FRAME_DEFAULT).toBe('biome-crystal_01');
    });

    // ── Ticket 08 (A4): brazier + lantern anims (distinct procedural sprites) ──
    it('the brazier has NO flicker frames — a static fixture-only sprite', () => {
      // The distinct brazier sprite (bowl of coals on a stand) still ships,
      // but as a STATIC fixture — the coal-glow "aliveness" is the light disk.
      expect(LIGHT_PROP_ANIMS.brazier).toEqual([]);
    });

    it('the lantern has NO flicker frames — a static fixture-only sprite', () => {
      // Same as the brazier: the enclosed flame reads via the light disk.
      expect(LIGHT_PROP_ANIMS.lantern).toEqual([]);
    });

    it('campfire + fireplace have EMPTY anim arrays (they reuse the static game/campfire frame)', () => {
      // Per the resolver: campfire + fireplace point at the existing game/campfire
      // frame. Their flicker lives in the LIGHT disk (the deferred-pipeline
      // flicker profile), NOT in a sprite anim. So the anim frame list is empty
      // for both — the renderer shows the static frame + the light disk flickers.
      expect(LIGHT_PROP_ANIMS.campfire.length).toBe(0);
      expect(LIGHT_PROP_ANIMS.fireplace.length).toBe(0);
    });

    it('EVERY flame kind ships an empty anim list (the static-fixture redesign contract)', () => {
      // The global pin: no flame kind may reintroduce sprite animation — the
      // "living fire" feel is the light disk's flicker, never the sprite.
      for (const frames of Object.values(LIGHT_PROP_ANIMS)) {
        expect(frames).toEqual([]);
      }
    });
  });

  describe('BIOME_GLOW_PULSE_FRAMES — static magical crystal', () => {
    it('is the single static biome-glow frame (the aura is the light disk)', () => {
      // Previously a 2-frame pulse; the redesign made it a single static
      // pixel-art crystal matching the fixture-only campfire.
      expect(BIOME_GLOW_PULSE_FRAMES.length).toBe(1);
      expect(BIOME_GLOW_PULSE_FRAMES[0]).toBe('biome-glow_01');
    });

    it('the first pulse frame matches the resolver default for biome-glow', () => {
      expect(BIOME_GLOW_PULSE_FRAMES[0]).toBe(resolveLightPropTexture('biome-glow')?.frame);
    });
  });
});
