/**
 * AUTO-GENERATED by scripts/asset-pipeline/build-audio-spritesheet.ts.
 * Do not edit by hand — re-run `pnpm --filter @sector-battle/client-v3
 * run build:audio-sprite` after changing anything under
 * `packages/client-v3/public/assets/audio`.
 */

/** Total number of audio markers in the sprite sheet: 53. */
export const AUDIO_SPRITE_MARKER_COUNT = 53;

/** Sorted list of every marker name (clip stem) in the sprite sheet. */
export const AUDIO_SPRITE_MARKERS = [
  'footstep_concrete_000',
  'footstep_concrete_001',
  'footstep_concrete_002',
  'footstep_concrete_003',
  'footstep_concrete_004',
  'impactbell_heavy_001',
  'impactbell_heavy_002',
  'impactbell_heavy_003',
  'impactbell_heavy_004',
  'impactgeneric_light_000',
  'impactglass_heavy_000',
  'impactmetal_heavy_000',
  'impactmetal_heavy_001',
  'impactmetal_heavy_002',
  'impactmetal_heavy_003',
  'impactpunch_heavy_000',
  'impactpunch_heavy_001',
  'impactpunch_heavy_002',
  'impactpunch_heavy_003',
  'impactpunch_medium_000',
  'impactpunch_medium_001',
  'impactsoft_medium_000',
  'impactwood_heavy_000',
  'impactwood_heavy_001',
  'impactwood_heavy_002',
  'impactwood_light_000',
  'impactwood_medium_000',
  'click_001',
  'click_003',
  'confirmation_001',
  'confirmation_002',
  'glitch_001',
  'maximize_001',
  'maximize_002',
  'maximize_003',
  'minimize_001',
  'open_001',
  'open_003',
  'switch_001',
  'switch_002',
  'tick_001',
  'tick_002',
  'jingles_steel_00',
  'game_over',
  'mission_plausible',
  'wacky_waiting',
  'retro_beat',
  '1',
  '2',
  '3',
  'go',
  'hurry_up',
  'power_up',
] as const;

/**
 * Phaser audio-sprite manifest path (relative to the client public root).
 * Load via `scene.load.audioSprite(AUDIO_SPRITE_KEY, AUDIO_SPRITE_JSON_PATH)`.
 */
export const AUDIO_SPRITE_JSON_PATH = 'assets/audio/spritesheet/audiosprite.json';

/** Phaser audio-cache key for the loaded sprite sheet. */
export const AUDIO_SPRITE_KEY = 'audio-sprite';

/**
 * SFX audio key → list of sprite markers (variants). Randomised at play.
 * Derived from AssetManifest.sfx — same files, same order.
 */
export const SFX_MARKER_MAP: Record<string, string[]> = {
  hit_melee: [
    'impactpunch_heavy_000',
    'impactpunch_heavy_001',
    'impactpunch_heavy_002',
    'impactpunch_heavy_003',
  ],
  hit_shield: ['impactmetal_heavy_001', 'impactmetal_heavy_002', 'impactmetal_heavy_003'],
  hit_thrown: ['impactwood_heavy_000', 'impactwood_heavy_001', 'impactwood_heavy_002'],
  dash: ['switch_002'],
  pickup_weapon: ['confirmation_001'],
  pickup_powerup: ['confirmation_002'],
  chest_open: ['open_001'],
  chest_rare: ['open_003'],
  player_kill: ['impactpunch_heavy_001'],
  player_hurt: ['impactpunch_medium_000', 'impactpunch_medium_001', 'impactsoft_medium_000'],
  player_death: ['impactbell_heavy_002'],
  player_stagger: ['impactsoft_medium_000'],
  weapon_break: ['impactmetal_heavy_000'],
  weapon_switch: ['switch_001'],
  weapon_drop: ['impactwood_light_000'],
  wall_hit: ['impactpunch_medium_001', 'impactwood_medium_000'],
  trap_trigger: ['impactmetal_heavy_000'],
  trap_spike: ['impactmetal_heavy_000'],
  trap_fire: ['impactglass_heavy_000'],
  trap_teleport: ['glitch_001'],
  trap_reveal: ['click_001'],
  zone_damage: ['impactgeneric_light_000'],
  zone_warning: ['tick_001'],
  zone_shrink: ['maximize_003'],
  countdown_beep: ['tick_002'],
  match_start: ['maximize_001'],
  countdown_go: ['maximize_002'],
  victory: ['maximize_002'],
  defeat: ['impactbell_heavy_001'],
  footstep: [
    'footstep_concrete_000',
    'footstep_concrete_001',
    'footstep_concrete_002',
    'footstep_concrete_003',
    'footstep_concrete_004',
  ],
  powerup_activate: ['jingles_steel_00'],
  spawn_protection_end: ['click_003'],
  siege_wall_drop: ['impactmetal_heavy_003'],
  siege_wall_warning: ['minimize_001'],
  barrel_explode: ['impactbell_heavy_003', 'impactbell_heavy_004'],
};

/** Music key → single sprite marker. Played with `loop: true`. */
export const MUSIC_MARKER_MAP: Record<string, string> = {
  menu: 'retro_beat',
  lobby: 'wacky_waiting',
  gameplay: 'mission_plausible',
  results: 'game_over',
};

/** Voiceover key → single sprite marker. */
export const VOICEOVER_MARKER_MAP: Record<string, string> = {
  countdown_3: '3',
  countdown_2: '2',
  countdown_1: '1',
  go: 'go',
  hurry_up: 'hurry_up',
  power_up: 'power_up',
};
