import Phaser from 'phaser';
import {
  AUDIO_SPRITE_KEY,
  AUDIO_SPRITE_JSON_PATH,
  MUSIC_MARKER_MAP,
  SFX_MARKER_MAP,
  VOICEOVER_MARKER_MAP,
} from '../assets/audio-sprite-markers.js';
import {
  attenuationForDistance,
  AUDIO_CATEGORY,
  type AudioCategory,
  BaseAudioService,
} from './AudioTypes.js';

/**
 * Scene-scoped audio service backed by a single Phaser audio sprite sheet.
 *
 * All SFX, music, and voiceover clips live in one concatenated `.ogg`
 * (`assets/audio/spritesheet/audiosprite.ogg`) described by
 * `assets/audio/spritesheet/audiosprite.json`. The companion
 * `audio-sprite-markers.ts` (auto-generated by
 * `scripts/asset-pipeline/build-audio-spritesheet.ts`) maps every logical
 * audio key (`'hit_melee'`, `'menu'`, `'countdown_3'`, …) to the sprite
 * marker(s) backing it — preserving the original randomised-variant
 * behaviour for SFX keys that have multiple source files.
 *
 * Re-run the generator whenever the contents of
 * `packages/client-v3/public/assets/audio` change.
 */
export class AudioService extends BaseAudioService {
  private scene: Phaser.Scene;
  /** Live local-player world position (shared mutable ref with GameState). */
  private readonly localPos: { x: number; y: number };
  private loaded = false;
  private activeCount = 0;
  private currentMusic: Phaser.Sound.BaseSound | null = null;
  private currentVoiceover: Phaser.Sound.BaseSound | null = null;

  constructor(scene: Phaser.Scene, localPos: { x: number; y: number }) {
    super();
    this.scene = scene;
    this.localPos = localPos;
  }

  loadAll(): void {
    // One load call for the entire audio catalogue — the JSON manifest lists
    // every marker, the audio file is the concatenated sprite sheet.
    if (!this.scene.cache.audio.exists(AUDIO_SPRITE_KEY)) {
      this.scene.load.audioSprite(AUDIO_SPRITE_KEY, AUDIO_SPRITE_JSON_PATH);
    }
    this.loaded = true;
  }

  play(key: string, volume = 0.5): void {
    if (!this.loaded || this.activeCount >= 8) return;
    const markers = SFX_MARKER_MAP[key];
    if (!markers || markers.length === 0) return;
    const marker = markers[Math.floor(Math.random() * markers.length)]!;
    if (!this.scene.cache.audio.exists(AUDIO_SPRITE_KEY)) return;
    this.activeCount++;
    try {
      // addAudioSprite wraps the cached decoded buffer (cheap — no re-decode)
      // and registers every marker from the manifest. We play the chosen
      // marker and auto-destroy on complete, mirroring the previous per-file
      // one-shot semantics while keeping the activeCount concurrency cap.
      const sound = this.scene.sound.addAudioSprite(AUDIO_SPRITE_KEY, { volume });
      sound.once('complete', () => {
        this.activeCount = Math.max(0, this.activeCount - 1);
        sound.destroy();
      });
      sound.play(marker);
    } catch {
      this.activeCount = Math.max(0, this.activeCount - 1);
    }
  }

  playAt(key: string, x: number, y: number, baseVolume = 0.5, category?: AudioCategory): void {
    const cat = category ?? AUDIO_CATEGORY[key] ?? 'normal';
    const dx = x - this.localPos.x;
    const dy = y - this.localPos.y;
    const dist = Math.sqrt(dx * dx + dy * dy);
    const volume = attenuationForDistance(dist, baseVolume, cat);
    if (volume === null) return; // beyond hearing range — skip entirely
    this.play(key, volume);
  }

  playVoiceover(key: string): void {
    if (!this.loaded) return;
    if (this.currentVoiceover && this.currentVoiceover.isPlaying) {
      this.currentVoiceover.stop();
      this.currentVoiceover.destroy();
      this.currentVoiceover = null;
    }
    const marker = VOICEOVER_MARKER_MAP[key];
    if (!marker || !this.scene.cache.audio.exists(AUDIO_SPRITE_KEY)) return;
    try {
      const sound = this.scene.sound.addAudioSprite(AUDIO_SPRITE_KEY, { volume: 0.8 });
      sound.once('complete', () => {
        this.currentVoiceover = null;
      });
      this.currentVoiceover = sound;
      sound.play(marker);
    } catch {
      this.currentVoiceover = null;
    }
  }

  playMusic(key?: string): void {
    if (!key) {
      this.stopMusic();
      return;
    }
    this.stopMusic();
    if (!this.loaded) return;
    const marker = MUSIC_MARKER_MAP[key];
    if (!marker || !this.scene.cache.audio.exists(AUDIO_SPRITE_KEY)) return;
    try {
      // NOTE: `loop: true` MUST be passed at play time, not to addAudioSprite.
      // addAudioSprite force-resets `loop` to false on every per-marker config
      // (it reads the JSON marker's `loop` field, defaulting to false), so a
      // global loop flag on addAudioSprite is silently discarded. BaseSound.play
      // applies the play-time config AFTER the marker config, so { loop: true }
      // here correctly overrides the marker's loop:false.
      const sound = this.scene.sound.addAudioSprite(AUDIO_SPRITE_KEY, { volume: 0.3 });
      this.currentMusic = sound;
      sound.play(marker, { loop: true });
    } catch {
      this.currentMusic = null;
    }
  }

  stopMusic(): void {
    if (this.currentMusic) {
      if (this.currentMusic.isPlaying) this.currentMusic.stop();
      this.currentMusic.destroy();
      this.currentMusic = null;
    }
  }

  destroy(): void {
    this.stopMusic();
    if (this.currentVoiceover) {
      if (this.currentVoiceover.isPlaying) this.currentVoiceover.stop();
      this.currentVoiceover.destroy();
      this.currentVoiceover = null;
    }
    this.activeCount = 0;
    this.loaded = false;
  }
}
