/* oxlint-disable max-lines */
/**
 * Pure weapon definition data — exempt from the 450-line limit.
 * All 16 weapon definitions used by WeaponRegistry.
 */
import { WeaponType } from '../enums/WeaponType.js';
import { AttackType } from '../enums/AttackType.js';
import { type WeaponDefinition, DURABILITY_BY_TIER } from './Weapon.js';

export function getDefaultDefinitions(): Map<WeaponType, WeaponDefinition> {
  const definitions = new Map<WeaponType, WeaponDefinition>();

  definitions.set(WeaponType.FISTS, {
    type: WeaponType.FISTS,
    visual: {
      scale: 1,
      rotationOffset: 0,
      handOffset: 0,
      originX: 0.5,
      originY: 0.5,
      flipX: false,
    },
    name: 'Fists',
    tier: null,
    attackType: AttackType.ARC,
    canThrow: false,
    durabilityByTier: DURABILITY_BY_TIER,
    baseStats: {
      hitStaggerMs: 0,
      damage: 5,
      destructibleDamage: 2,
      range: 128,
      cooldown: 400,
      knockback: 0,
      bounces: 0,
      tier: null,
      attackType: AttackType.ARC,
      weightTier: 0,
      windupMs: 50,
      arcAngle: Math.PI / 2,
    },
  });

  definitions.set(WeaponType.DAGGER, {
    type: WeaponType.DAGGER,
    visual: {
      scale: 1,
      originX: 0.5,
      originY: 0.76,
      flipX: false,
      rotationOffset: Math.PI / 2,
      handOffset: 16,
    },
    name: 'Dagger',
    tier: null,
    attackType: AttackType.ARC,
    canThrow: true,
    durabilityByTier: DURABILITY_BY_TIER,
    baseStats: {
      hitStaggerMs: 0,
      damage: 8,
      destructibleDamage: 3,
      range: 160,
      cooldown: 300,
      knockback: 5,
      bounces: 0,
      tier: null,
      attackType: AttackType.ARC,
      weightTier: 0,
      windupMs: 100,
      arcAngle: Math.PI / 2,
      throwSpeed: 2000,
      throwRange: 640,
      throwKnockback: 5,
    },
  });

  definitions.set(WeaponType.SHORT_SWORD, {
    type: WeaponType.SHORT_SWORD,
    visual: {
      scale: 1,
      originX: 0.5,
      originY: 0.78,
      flipX: false,
      rotationOffset: Math.PI / 2,
      handOffset: 20,
    },
    name: 'Short Sword',
    tier: null,
    attackType: AttackType.ARC,
    canThrow: true,
    durabilityByTier: DURABILITY_BY_TIER,
    baseStats: {
      hitStaggerMs: 60,
      damage: 12,
      destructibleDamage: 4,
      range: 192,
      cooldown: 450,
      knockback: 8,
      bounces: 0,
      tier: null,
      attackType: AttackType.ARC,
      weightTier: 1,
      windupMs: 150,
      arcAngle: Math.PI / 2,
      throwSpeed: 1500,
      throwRange: 800,
      throwKnockback: 8,
    },
  });

  definitions.set(WeaponType.LONG_SWORD, {
    type: WeaponType.LONG_SWORD,
    visual: {
      scale: 1,
      originX: 0.5,
      originY: 0.86,
      flipX: false,
      rotationOffset: Math.PI / 2,
      handOffset: 24,
    },
    name: 'Long Sword',
    tier: null,
    attackType: AttackType.ARC,
    canThrow: true,
    durabilityByTier: DURABILITY_BY_TIER,
    baseStats: {
      hitStaggerMs: 120,
      damage: 18,
      destructibleDamage: 5,
      range: 224,
      cooldown: 600,
      knockback: 15,
      bounces: 0,
      tier: null,
      attackType: AttackType.ARC,
      weightTier: 2,
      windupMs: 200,
      arcAngle: Math.PI / 2,
      throwSpeed: 1200,
      throwRange: 640,
      throwKnockback: 15,
    },
  });

  definitions.set(WeaponType.HAMMER, {
    type: WeaponType.HAMMER,
    visual: {
      scale: 1,
      originX: 0.5,
      originY: 0.85,
      flipX: false,
      rotationOffset: Math.PI / 2,
      handOffset: 24,
    },
    name: 'Hammer',
    tier: null,
    attackType: AttackType.ARC,
    canThrow: true,
    durabilityByTier: DURABILITY_BY_TIER,
    baseStats: {
      hitStaggerMs: 280,
      damage: 22,
      destructibleDamage: 10,
      range: 192,
      cooldown: 800,
      knockback: 25,
      bounces: 0,
      tier: null,
      attackType: AttackType.ARC,
      weightTier: 3,
      windupMs: 200,
      arcAngle: Math.PI / 2,
      throwSpeed: 1000,
      throwRange: 640,
      throwKnockback: 25,
    },
  });

  definitions.set(WeaponType.LARGE_AXE, {
    type: WeaponType.LARGE_AXE,
    visual: {
      scale: 1,
      originX: 0.5,
      originY: 0.85,
      flipX: false,
      rotationOffset: Math.PI / 2,
      handOffset: 24,
    },
    name: 'Large Axe',
    tier: null,
    attackType: AttackType.ARC,
    canThrow: true,
    durabilityByTier: DURABILITY_BY_TIER,
    baseStats: {
      hitStaggerMs: 170,
      damage: 20,
      destructibleDamage: 6,
      range: 208,
      cooldown: 700,
      knockback: 20,
      bounces: 0,
      tier: null,
      attackType: AttackType.ARC,
      weightTier: 2,
      windupMs: 200,
      arcAngle: Math.PI / 2,
      throwSpeed: 1000,
      throwRange: 540,
      throwKnockback: 20,
    },
  });

  definitions.set(WeaponType.BLADED_AXE, {
    type: WeaponType.BLADED_AXE,
    visual: {
      scale: 1,
      originX: 0.5,
      originY: 0.85,
      flipX: false,
      rotationOffset: Math.PI / 2,
      handOffset: 24,
    },
    name: 'Bladed Axe',
    tier: null,
    attackType: AttackType.ARC,
    canThrow: true,
    durabilityByTier: DURABILITY_BY_TIER,
    baseStats: {
      hitStaggerMs: 150,
      damage: 25,
      destructibleDamage: 7,
      range: 224,
      cooldown: 750,
      knockback: 22,
      bounces: 0,
      tier: null,
      attackType: AttackType.ARC,
      weightTier: 2,
      windupMs: 200,
      arcAngle: Math.PI / 2,
      throwSpeed: 1000,
      throwRange: 800,
      throwKnockback: 22,
    },
  });

  definitions.set(WeaponType.DOUBLE_AXE, {
    type: WeaponType.DOUBLE_AXE,
    visual: {
      scale: 1,
      originX: 0.5,
      originY: 0.83,
      flipX: false,
      rotationOffset: Math.PI / 2,
      handOffset: 24,
    },
    name: 'Double Axe',
    tier: null,
    attackType: AttackType.ARC,
    canThrow: true,
    durabilityByTier: DURABILITY_BY_TIER,
    baseStats: {
      hitStaggerMs: 220,
      damage: 30,
      destructibleDamage: 10,
      range: 240,
      cooldown: 850,
      knockback: 30,
      bounces: 0,
      tier: null,
      attackType: AttackType.ARC,
      weightTier: 3,
      windupMs: 200,
      arcAngle: Math.PI / 2,
      throwSpeed: 1000,
      throwRange: 480,
      throwKnockback: 30,
    },
  });

  definitions.set(WeaponType.SPEAR, {
    type: WeaponType.SPEAR,
    visual: {
      scale: 1.3,
      originX: 0.5,
      originY: 0.9,
      flipX: false,
      rotationOffset: Math.PI / 2,
      handOffset: 5,
    },
    name: 'Spear',
    tier: null,
    attackType: AttackType.LINE,
    canThrow: true,
    durabilityByTier: DURABILITY_BY_TIER,
    baseStats: {
      hitStaggerMs: 80,
      damage: 15,
      destructibleDamage: 4,
      range: 320,
      cooldown: 500,
      knockback: 10,
      bounces: 0,
      tier: null,
      attackType: AttackType.LINE,
      weightTier: 1,
      windupMs: 150,
      throwSpeed: 1600,
      throwRange: 1500,
      throwKnockback: 10,
    },
  });

  definitions.set(WeaponType.POLEARM, {
    type: WeaponType.POLEARM,
    visual: {
      scale: 1.4,
      originX: 0.5,
      originY: 0.89,
      flipX: false,
      rotationOffset: Math.PI / 2,
      handOffset: 6,
    },
    name: 'Polearm',
    tier: null,
    attackType: AttackType.LINE,
    canThrow: true,
    durabilityByTier: DURABILITY_BY_TIER,
    baseStats: {
      hitStaggerMs: 160,
      damage: 22,
      destructibleDamage: 5,
      range: 384,
      cooldown: 700,
      knockback: 20,
      bounces: 0,
      tier: null,
      attackType: AttackType.LINE,
      weightTier: 2,
      windupMs: 200,
      throwSpeed: 1300,
      throwRange: 1500,
      throwKnockback: 20,
    },
  });

  definitions.set(WeaponType.STAFF, {
    type: WeaponType.STAFF,
    visual: {
      scale: 1.2,
      originX: 0.5,
      originY: 0.87,
      flipX: false,
      rotationOffset: Math.PI / 2,
      handOffset: 4,
    },
    name: 'Staff',
    tier: null,
    attackType: AttackType.LINE,
    canThrow: true,
    durabilityByTier: DURABILITY_BY_TIER,
    baseStats: {
      hitStaggerMs: 60,
      damage: 10,
      destructibleDamage: 3,
      range: 288,
      cooldown: 400,
      knockback: 5,
      bounces: 0,
      tier: null,
      attackType: AttackType.LINE,
      weightTier: 0,
      windupMs: 150,
      throwSpeed: 1300,
      throwRange: 1000,
      throwKnockback: 5,
    },
  });

  definitions.set(WeaponType.THROWING_AXE, {
    type: WeaponType.THROWING_AXE,
    visual: {
      scale: 1,
      originX: 0.5,
      originY: 0.79,
      flipX: true,
      rotationOffset: Math.PI / 2,
      handOffset: 16,
    },
    name: 'Throwing Axe',
    tier: null,
    attackType: AttackType.THROWN,
    canThrow: true,
    durabilityByTier: DURABILITY_BY_TIER,
    meleeStats: {
      damage: 10,
      range: 160,
      cooldown: 400,
      knockback: 5,
      attackType: AttackType.ARC,
      arcAngle: Math.PI / 2,
      windupMs: 80,
    },
    baseStats: {
      hitStaggerMs: 90,
      damage: 15,
      destructibleDamage: 4,
      range: 800,
      cooldown: 500,
      knockback: 8,
      bounces: 3,
      tier: null,
      attackType: AttackType.THROWN,
      weightTier: 0,
      windupMs: 100,
      throwSpeed: 1800,
      throwRange: 1500,
      throwKnockback: 8,
    },
  });

  definitions.set(WeaponType.SHORT_BOW, {
    type: WeaponType.SHORT_BOW,
    visual: {
      scale: 1,
      originX: 0.5,
      originY: 0.5,
      flipX: false,
      rotationOffset: Math.PI / 2,
      handOffset: 20,
    },
    name: 'Short Bow',
    tier: null,
    attackType: AttackType.RANGED,
    canThrow: true,
    durabilityByTier: DURABILITY_BY_TIER,
    durabilityMultiplier: 1.5,
    baseStats: {
      hitStaggerMs: 40,
      damage: 10,
      destructibleDamage: 3,
      range: 1800,
      cooldown: 500,
      knockback: 3,
      bounces: 0,
      tier: null,
      attackType: AttackType.RANGED,
      weightTier: 3,
      windupMs: 150,
      projectileSpeed: 2000,
      throwSpeed: 1000,
      throwRange: 1200,
      throwKnockback: 3,
    },
  });

  definitions.set(WeaponType.CROSSBOW, {
    type: WeaponType.CROSSBOW,
    visual: {
      scale: 1,
      originX: 0.5,
      originY: 0.5,
      flipX: false,
      rotationOffset: Math.PI / 2,
      handOffset: 24,
    },
    name: 'Crossbow',
    tier: null,
    attackType: AttackType.RANGED,
    canThrow: true,
    durabilityByTier: DURABILITY_BY_TIER,
    durabilityMultiplier: 1.5,
    baseStats: {
      hitStaggerMs: 160,
      damage: 25,
      destructibleDamage: 10,
      range: 2000,
      cooldown: 1000,
      knockback: 12,
      bounces: 0,
      tier: null,
      attackType: AttackType.RANGED,
      weightTier: 3,
      windupMs: 200,
      projectileSpeed: 2000,
      throwSpeed: 1000,
      throwRange: 640,
      throwKnockback: 12,
    },
  });

  definitions.set(WeaponType.SMALL_SHIELD, {
    type: WeaponType.SMALL_SHIELD,
    visual: {
      scale: 1,
      originX: 0.5,
      originY: 0.6,
      flipX: false,
      rotationOffset: Math.PI / 2,
      // Shield arc sits just ahead of the hands' midpoint — hands grip its back
      handOffset: 10,
    },
    name: 'Small Shield',
    tier: null,
    attackType: AttackType.SHIELD,
    canThrow: true,
    durabilityByTier: DURABILITY_BY_TIER,
    durabilityMultiplier: 1.5,
    baseStats: {
      hitStaggerMs: 500,
      damage: 5,
      destructibleDamage: 4,
      range: 400,
      cooldown: 500,
      knockback: 50,
      bounces: 0,
      tier: null,
      attackType: AttackType.SHIELD,
      weightTier: 0,
      windupMs: 100,
      blockReduction: 1.0,
      blockArcDegrees: 90,
      staggerOnBreakMs: 300,
      isBoomerang: true,
      throwSpeed: 1200,
      throwRange: 1500,
      throwKnockback: 25,
    },
  });

  definitions.set(WeaponType.LARGE_SHIELD, {
    type: WeaponType.LARGE_SHIELD,
    visual: {
      scale: 1,
      originX: 0.5,
      originY: 0.6,
      flipX: false,
      rotationOffset: Math.PI / 2,
      // Shield arc sits just ahead of the hands' midpoint — hands grip its back
      handOffset: 12,
    },
    name: 'Large Shield',
    tier: null,
    attackType: AttackType.SHIELD,
    canThrow: true,
    durabilityByTier: DURABILITY_BY_TIER,
    durabilityMultiplier: 2.0,
    baseStats: {
      hitStaggerMs: 600,
      damage: 8,
      destructibleDamage: 10,
      range: 350,
      cooldown: 500,
      knockback: 50,
      bounces: 0,
      tier: null,
      attackType: AttackType.SHIELD,
      weightTier: 1,
      windupMs: 150,
      blockReduction: 1.0,
      blockArcDegrees: 180,
      staggerOnBreakMs: 300,
      isBoomerang: true,
      throwSpeed: 1200,
      throwRange: 1000,
      throwKnockback: 25,
    },
  });

  return definitions;
}
